services:
  #backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: film-collector-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/filmcollector
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  #frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: film-collector-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  #db
  db:
    image: bitnami/postgresql:14
    container_name: film-collector-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=filmcollector
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge